/**
 * Shared logic for the dev-only /arrange page, which drag-reorders photos,
 * moves them between collections, and hides them from the site. Persists to
 * photo-order.json and photo-overrides.json. The manifest itself stays
 * Instagram-truth (regenerated by sync-instagram); overrides are curation
 * layered on top so they survive re-syncs. Kept free of fs/Next imports so
 * tests can exercise it directly.
 */

export type OrderMap = Record<string, string[]>;

/**
 * Named single-image slots on the photography home page. Each maps to one
 * photo id; a missing/stale slot falls back to a deterministic frame so the
 * page never breaks. Instagram-strip slots are numbered strip1..strip6.
 */
export const FEATURED_SLOTS = [
  "collectionsFeature",
  "wideFrame",
  "strip1",
  "strip2",
  "strip3",
  "strip4",
  "strip5",
  "strip6",
] as const;

export type FeaturedSlot = (typeof FEATURED_SLOTS)[number];

/** Human labels + a short description for each home-page slot, for the UI. */
export const SLOT_META: Record<FeaturedSlot, { label: string; hint: string }> = {
  collectionsFeature: {
    label: "Home · feature card",
    hint: "Tall image in the “The work” block",
  },
  wideFrame: { label: "Home · wide band", hint: "Full-width panorama strip" },
  strip1: { label: "Instagram strip · 1", hint: "" },
  strip2: { label: "Instagram strip · 2", hint: "" },
  strip3: { label: "Instagram strip · 3", hint: "" },
  strip4: { label: "Instagram strip · 4", hint: "" },
  strip5: { label: "Instagram strip · 5", hint: "" },
  strip6: { label: "Instagram strip · 6", hint: "" },
};

export type Overrides = {
  /** photo id -> collection it should display under instead of its own */
  moves: Record<string, string>;
  /** photo ids removed from the site (files stay; the next sync would just re-download them) */
  hidden: string[];
  /** home-page slot -> photo id chosen for it */
  featured: Partial<Record<FeaturedSlot, string>>;
};

type PhotoRef = { id: string; collection: string };

/**
 * The site's view of the manifest: hidden photos dropped, moved photos
 * re-collected. Tolerates stale ids (a re-sync can rename or drop posts) —
 * the round-trip test flags them, the runtime shrugs them off.
 */
export function applyOverrides<T extends PhotoRef>(
  photos: readonly T[],
  overrides: Overrides,
): T[] {
  const hidden = new Set(overrides.hidden);
  return photos
    .filter((p) => !hidden.has(p.id))
    .map((p) =>
      overrides.moves[p.id] ? { ...p, collection: overrides.moves[p.id] } : p,
    );
}

/** Returns human-readable problems; an empty array means the order is valid. */
export function validateOrder(
  input: unknown,
  photos: readonly PhotoRef[],
): string[] {
  if (
    typeof input !== "object" ||
    input === null ||
    Array.isArray(input)
  ) {
    return ["order must be an object mapping collection ids to photo id arrays"];
  }
  const errors: string[] = [];
  for (const [collection, ids] of Object.entries(input)) {
    if (!Array.isArray(ids) || ids.some((id) => typeof id !== "string")) {
      errors.push(`${collection}: expected an array of photo ids`);
      continue;
    }
    if (new Set(ids).size !== ids.length) {
      errors.push(`${collection}: duplicate photo id`);
    }
    for (const id of ids) {
      if (!photos.some((p) => p.id === id && p.collection === collection)) {
        errors.push(`${collection}: unknown photo id ${id}`);
      }
    }
  }
  return errors;
}

/** Validates against the base (pre-override) manifest. */
export function validateOverrides(
  input: unknown,
  photos: readonly PhotoRef[],
  allowedCollections: readonly string[],
): string[] {
  const overrides = input as Partial<Overrides> | null;
  if (typeof overrides !== "object" || overrides === null) {
    return ["overrides must be an object with moves, hidden and featured"];
  }
  const errors: string[] = [];
  const { moves = {}, hidden = [], featured = {} } = overrides;

  if (
    typeof moves !== "object" ||
    moves === null ||
    Array.isArray(moves) ||
    Object.values(moves).some((c) => typeof c !== "string")
  ) {
    errors.push("moves must map photo ids to collection ids");
  } else {
    for (const [id, collection] of Object.entries(moves)) {
      if (!photos.some((p) => p.id === id)) {
        errors.push(`moves: unknown photo id ${id}`);
      }
      if (!allowedCollections.includes(collection)) {
        errors.push(`moves: unknown collection ${collection}`);
      }
    }
  }

  if (!Array.isArray(hidden) || hidden.some((id) => typeof id !== "string")) {
    errors.push("hidden must be an array of photo ids");
  } else {
    if (new Set(hidden).size !== hidden.length) {
      errors.push("hidden: duplicate photo id");
    }
    for (const id of hidden) {
      if (!photos.some((p) => p.id === id)) {
        errors.push(`hidden: unknown photo id ${id}`);
      }
    }
  }

  if (
    typeof featured !== "object" ||
    featured === null ||
    Array.isArray(featured) ||
    Object.values(featured).some((id) => typeof id !== "string")
  ) {
    errors.push("featured must map slot names to photo ids");
  } else {
    const hiddenSet = new Set(Array.isArray(hidden) ? hidden : []);
    for (const [slot, id] of Object.entries(featured)) {
      if (!FEATURED_SLOTS.includes(slot as FeaturedSlot)) {
        errors.push(`featured: unknown slot ${slot}`);
      }
      if (!photos.some((p) => p.id === id)) {
        errors.push(`featured: unknown photo id ${id}`);
      } else if (hiddenSet.has(id as string)) {
        errors.push(`featured: ${slot} points at a hidden photo`);
      }
    }
  }

  return errors;
}

/**
 * Canonical form for photo-order.json: drop empty lists and lists that match
 * the effective import order, and sort keys so saves diff cleanly in git.
 */
export function normalizeOrder(
  order: OrderMap,
  photos: readonly PhotoRef[],
): OrderMap {
  const normalized: OrderMap = {};
  for (const collection of Object.keys(order).sort()) {
    const ids = order[collection];
    if (!ids.length) continue;
    const manifestIds = photos
      .filter((p) => p.collection === collection)
      .map((p) => p.id);
    const isImportOrder =
      ids.length === manifestIds.length &&
      ids.every((id, i) => id === manifestIds[i]);
    if (!isImportOrder) normalized[collection] = ids;
  }
  return normalized;
}

/**
 * Canonical form for photo-overrides.json: no-op moves (back to the photo's
 * own collection) and stale ids dropped, keys and lists sorted.
 */
export function normalizeOverrides(
  overrides: Overrides,
  photos: readonly PhotoRef[],
): Overrides {
  const moves: Record<string, string> = {};
  for (const id of Object.keys(overrides.moves).sort()) {
    const photo = photos.find((p) => p.id === id);
    if (photo && photo.collection !== overrides.moves[id]) {
      moves[id] = overrides.moves[id];
    }
  }
  const hidden = [...new Set(overrides.hidden)]
    .filter((id) => photos.some((p) => p.id === id))
    .sort();
  const hiddenSet = new Set(hidden);
  const featured: Partial<Record<FeaturedSlot, string>> = {};
  for (const slot of FEATURED_SLOTS) {
    const id = overrides.featured?.[slot];
    // Keep only slots that point at a real, visible photo.
    if (id && photos.some((p) => p.id === id) && !hiddenSet.has(id)) {
      featured[slot] = id;
    }
  }
  return { moves, hidden, featured };
}

export const serializeJson = (value: unknown): string =>
  JSON.stringify(value, null, 2) + "\n";
