"use client";

import { useState, useEffect, useCallback } from "react";

interface DiagramItem {
  src: string;
  index: string;
  topic: string;
  source: string;
  title: string;
  blurb: string;
  logic: string;
  challenge: string;
  span: string;
}

interface DiagramGroup {
  id: string;
  eyebrow: string;
  title: string;
  italic: string;
  items: DiagramItem[];
}

// Sourced from architecture/data-flows.md (verified). PNGs live in
// public/diagrams/, generated by architecture/generate_diagrams.py.
const GROUPS: DiagramGroup[] = [
  {
    id: "overview",
    eyebrow: "the whole stack",
    title: "One diagram,",
    italic: "every layer.",
    items: [
      {
        src: "/diagrams/06_full_architecture.png",
        index: "00",
        topic: "overview",
        source: "data-flows.md",
        title: "Full architecture",
        blurb:
          "Edge, the EKS polyglot mesh, data services, serverless fan-out, and the LGTM observability stack — drawn from the verified service map.",
        logic:
          "One picture grouped by layer (edge → compute → data → serverless → observability) so a reader can trace a request top to bottom without hunting. CI/CD and the client libraries sit off to the side because they are build-time, not part of the runtime request path.",
        challenge:
          "Keeping it honest and readable at once. Every node and edge maps to real code or Terraform; the hard part was spacing 30+ services so the crossings stay legible instead of becoming a hairball.",
        span: "lg:col-span-12",
      },
    ],
  },
  {
    id: "flows",
    eyebrow: "data in motion",
    title: "Four flows,",
    italic: "end to end.",
    items: [
      // Mesh is tall (6 services) → pairs with the short projection card.
      {
        src: "/diagrams/01_mesh_fanout.png",
        index: "01",
        topic: "mesh",
        source: "api-gateway/app.ts",
        title: "Mesh fan-out",
        blurb:
          "One place-order crosses six languages: api-gateway → pricing → inventory → fraud → payment → ledger.",
        logic:
          "A deliberately polyglot chain (Go, Python, Java, Node) to exercise cross-language tracing and service-to-service auth. The api-gateway is a thin BFF that calls each hop in order; payment posts to the ledger itself rather than the gateway, so failures surface where they happen.",
        challenge:
          "Trust between services. Each hop is HMAC-signed (timestamp.tenant.body.secret) so an internal call can't be forged, and the synthetic tenant tag has to propagate through every language's OTel SDK to stitch one trace.",
        span: "lg:col-span-5",
      },
      {
        src: "/diagrams/03_projection_read.png",
        index: "02",
        topic: "cqrs",
        source: "projection-worker",
        title: "Projection read",
        blurb:
          "A second Kinesis consumer builds a per-tenant in-memory read model.",
        logic:
          "CQRS in miniature: the same order-event stream feeds a separate Python worker that folds events into a fast read model, keeping reads off the write path. It is an independent consumer so it can be rebuilt or scaled without touching order-api.",
        challenge:
          "Per-shard iteration and tenant isolation. The poller tracks a LATEST iterator per shard and the model is keyed by tenant, so a replay or a noisy tenant can't corrupt another's view.",
        span: "lg:col-span-7",
      },
      // Async + saga are short and very wide → full-width rows of their own.
      {
        src: "/diagrams/02_async_events.png",
        index: "03",
        topic: "async",
        source: "mesh-events",
        title: "Async events",
        blurb:
          "order-api → Kinesis → enrichment lambda → EventBridge → analytics lambda (EMF metrics).",
        logic:
          "Post-commit fan-out: the order commits first, then the event publishes to Kinesis so analytics and downstream consumers run off the hot path. EventBridge sits in the middle as a routing layer so new consumers attach without changing the producer. Analytics emits CloudWatch EMF so metrics appear with zero PutMetricData calls.",
        challenge:
          "Not letting telemetry break orders. The Kinesis publish is best-effort and runs after the DB commit; if it fails, order-api writes an audit row (result=kinesis_publish_failed) instead of rolling back a paid order.",
        span: "lg:col-span-12",
      },
      {
        src: "/diagrams/04_checkout_saga.png",
        index: "04",
        topic: "saga",
        source: "storefront-checkout",
        title: "Checkout saga",
        blurb:
          "The storefront creates the order, then Step Functions enqueues the confirmation email.",
        logic:
          "The authenticated storefront route creates the order before starting the state machine, so end-user writes never ride an anonymous tenant path. The Step Functions workflow is intentionally tiny — one EnqueueEmail state onto SQS — because durable delivery, not orchestration, is what needs the state machine.",
        challenge:
          "Resisting the urge to put the DB write inside the saga. Keeping order creation in the request and the SF workflow at a single durable step avoids a distributed transaction; SQS + a DLQ (maxReceiveCount 3) handle email retries without blocking checkout.",
        span: "lg:col-span-12",
      },
    ],
  },
  {
    id: "concerns",
    eyebrow: "cross-cutting",
    title: "Every concern,",
    italic: "on its own canvas.",
    items: [
      // Networking is very tall (stacked VPC) → give it a narrow column beside
      // the squarer observability card so neither leaves dead space.
      {
        src: "/diagrams/07_networking.png",
        index: "05",
        topic: "networking",
        source: "networking.md",
        title: "Networking",
        blurb:
          "VPC 10.0.0.0/16 across two AZs — public, private, and DB subnets with SG-scoped paths.",
        logic:
          "Classic three-tier isolation: only the ALB lives in public subnets, pods run private, and the database sits in its own subnet tier reachable only from the pods. Two AZs give Multi-AZ failover; security groups (not just NACLs) gate each hop.",
        challenge:
          "Egress without exposure. Private pods reach AWS APIs through NAT gateways, and the NetworkPolicy had to emit real CIDRs even when db_subnet_cidrs is null, so the migration job can still reach Postgres on 5432 once CNI policy enforcement is on.",
        span: "lg:col-span-5",
      },
      {
        src: "/diagrams/05_observability.png",
        index: "06",
        topic: "observability",
        source: "modules/observability",
        title: "Observability",
        blurb:
          "OTel and yace/CloudWatch feed Mimir, Loki, and Tempo — all surfaced in Grafana.",
        logic:
          "Two ingest paths, one query surface. App spans/logs/metrics flow through the OTel Collector into the LGTM stack; AWS-native metrics (RDS, ALB, Lambda) come in via yace scraping CloudWatch into Prometheus. Everything lands in Mimir/Loki/Tempo so Grafana queries it uniformly.",
        challenge:
          "Cost and uniformity. Querying CloudWatch directly from Grafana would bill per dashboard load, so yace scrapes on an interval into Prometheus instead — one query language, predictable cost. The Tempo metrics-generator also feeds the live service map.",
        span: "lg:col-span-7",
      },
      // Security + data layer are both wide/landscape → pair evenly.
      {
        src: "/diagrams/08_security.png",
        index: "07",
        topic: "security",
        source: "modules/security",
        title: "Security",
        blurb:
          "WAF, Cognito, IRSA → Secrets → KMS, Postgres force-RLS, internal HMAC, and GuardDuty.",
        logic:
          "Defense in depth, layer by layer. WAF at the edge, Cognito for identity, IRSA so pods get scoped AWS creds without static keys, Secrets Manager + KMS for secrets, and force-RLS in Postgres so tenant isolation holds even if an app query forgets a WHERE clause.",
        challenge:
          "Making RLS unbypassable. The app role uses FORCE ROW LEVEL SECURITY and the tenant is bound per-request via current_setting('app.tenant_id'), so even the table owner can't read across tenants. Internal service calls are HMAC-gated separately from the user JWT path.",
        span: "lg:col-span-7",
      },
      {
        src: "/diagrams/09_data_layer.png",
        index: "08",
        topic: "data",
        source: "data-flows.md",
        title: "Data layer",
        blurb:
          "RDS Postgres, the DynamoDB cart, and the Kinesis stream with its two consumers.",
        logic:
          "Right store for each job: Postgres for orders/audit/idempotency where transactions and RLS matter, DynamoDB for the high-churn cart where a key-value store with TTL fits, and Kinesis as the event backbone two independent consumers read from.",
        challenge:
          "Exactly-once-ish semantics on a paid action. Idempotency keys (tenant-scoped, 24h window) fence retries on POST /order, and the cart's guest UUID has a collision check so two anonymous sessions never share a cart.",
        span: "lg:col-span-5",
      },
    ],
  },
  {
    id: "cicd",
    eyebrow: "ship & provision",
    title: "Two pipelines,",
    italic: "gated and signed.",
    items: [
      // Both pipelines are short + very wide → full-width rows read best.
      {
        src: "/diagrams/10_cicd_app.png",
        index: "09",
        topic: "app deploy",
        source: "app.yml",
        title: "CI/CD — app deploy",
        blurb:
          "test → build + Cosign sign → ECR → Trivy scan → budget check → verified deploy → EKS rollout.",
        logic:
          "Supply-chain integrity end to end. Images are Cosign-signed at build (keyless, via GitHub OIDC — no private key), scanned by Trivy, and the deploy step verifies the signature before rollout, so only an image this pipeline built and signed can reach the cluster. Deploys are digest-pinned, never tag-based.",
        challenge:
          "No long-lived AWS keys, no unsigned images. GitHub OIDC federates into an IAM role per environment instead of stored secrets, and the deploy job re-verifies the Cosign signature so a promoted digest can't skip the gate.",
        span: "lg:col-span-12",
      },
      {
        src: "/diagrams/11_cicd_infra.png",
        index: "10",
        topic: "infra",
        source: "infra.yml",
        title: "CI/CD — infra",
        blurb:
          "quality → plan → security-scan → prod approval gate → apply → compliance-scan.",
        logic:
          "Terraform with a human in the loop for prod. fmt/validate/tflint catch quality, tfsec/trivy/checkov catch misconfigurations, then a GitHub environment gate requires explicit approval before apply. A post-apply compliance scan confirms the result matches policy.",
        challenge:
          "Least privilege in CI without blocking it. The deploy role trusts only protected branches and environment subjects (no PR contexts), so a fork PR can plan but can never apply; drift detection runs per-stack so a dev-only change doesn't page on prod.",
        span: "lg:col-span-12",
      },
    ],
  },
];

interface DiagramCardProps {
  item: DiagramItem;
  onOpen: (item: DiagramItem) => void;
}

function DiagramCard({ item, onOpen }: DiagramCardProps) {
  return (
    <button
      type="button"
      onClick={() => onOpen(item)}
      className={`group relative flex flex-col gap-4 overflow-hidden rounded-2xl border border-border-default/80 bg-bg-raised/55 p-6 text-left backdrop-blur-md transition-all duration-300 hover:-translate-y-1 hover:border-brand-500/40 hover:shadow-[0_30px_80px_-20px_rgba(45,212,191,0.18)] ${item.span}`}
    >
      <header className="flex items-start justify-between gap-3">
        <p className="font-mono text-[11px] uppercase tracking-[0.18em] text-fg-subtle">
          diagram {item.index} · {item.topic}
        </p>
        <span className="font-mono text-[10px] text-fg-subtle">{item.source}</span>
      </header>

      <div className="overflow-hidden rounded-xl border border-border-muted/60 bg-bg-base/60">
        <img
          src={item.src}
          alt={item.title}
          loading="lazy"
          className="h-auto w-full object-contain transition-transform duration-300 group-hover:scale-[1.01]"
        />
      </div>

      <div className="flex flex-col gap-2">
        <h3 className="text-2xl font-medium leading-tight tracking-tight text-fg-base">
          {item.title}
        </h3>
        <p className="max-w-prose text-sm text-fg-muted">{item.blurb}</p>
      </div>

      <dl className="flex flex-col gap-3 border-t border-border-muted/50 pt-4">
        <div>
          <dt className="font-mono text-[10px] uppercase tracking-[0.16em] text-brand-400">
            logic
          </dt>
          <dd className="mt-1 text-[13px] leading-relaxed text-fg-muted">
            {item.logic}
          </dd>
        </div>
        <div>
          <dt className="font-mono text-[10px] uppercase tracking-[0.16em] text-fg-subtle">
            challenge
          </dt>
          <dd className="mt-1 text-[13px] leading-relaxed text-fg-muted">
            {item.challenge}
          </dd>
        </div>
      </dl>

      <span className="font-mono text-[11px] text-brand-400 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
        click to enlarge ↗
      </span>

      <span
        aria-hidden
        className="pointer-events-none absolute inset-x-6 bottom-4 h-px origin-left scale-x-0 bg-brand-500/60 transition-transform duration-300 group-hover:scale-x-100"
      />
    </button>
  );
}

export function DiagramGallery() {
  const [lightbox, setLightbox] = useState<DiagramItem | null>(null);
  const close = useCallback(() => setLightbox(null), []);

  useEffect(() => {
    if (!lightbox) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") close();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [lightbox, close]);

  return (
    <>
      {GROUPS.map((group) => (
        <section
          key={group.id}
          id={group.id}
          className="border-b border-border-muted/60 py-24 last:border-b-0"
        >
          <div className="mx-auto max-w-7xl px-6">
            <p className="font-mono text-[11px] uppercase tracking-[0.18em] text-fg-subtle">
              {group.eyebrow}
            </p>
            <h2 className="mt-3 max-w-2xl text-4xl font-medium leading-tight tracking-tight text-fg-base sm:text-5xl">
              {group.title}{" "}
              <span className="display-italic text-brand-400">{group.italic}</span>
            </h2>

            <div className="mt-12 grid grid-cols-1 items-start gap-6 lg:grid-cols-12">
              {group.items.map((item) => (
                <DiagramCard key={item.src} item={item} onOpen={setLightbox} />
              ))}
            </div>
          </div>
        </section>
      ))}

      {lightbox ? (
        <div
          role="dialog"
          aria-modal="true"
          aria-label={lightbox.title}
          onClick={close}
          className="fixed inset-0 z-50 flex flex-col items-center justify-center gap-4 bg-bg-base/90 p-6 backdrop-blur-md"
        >
          <div className="flex w-full max-w-6xl items-center justify-between">
            <p className="font-mono text-[11px] uppercase tracking-[0.18em] text-fg-subtle">
              diagram {lightbox.index} · {lightbox.topic} ·{" "}
              <span className="text-fg-muted">{lightbox.title}</span>
            </p>
            <button
              type="button"
              onClick={close}
              className="rounded-md border border-border-default bg-bg-raised/60 px-3 py-1.5 font-mono text-[12px] text-fg-muted transition-colors hover:border-brand-500/40 hover:text-fg-base"
            >
              close ✕
            </button>
          </div>
          <img
            src={lightbox.src}
            alt={lightbox.title}
            onClick={(e) => e.stopPropagation()}
            className="max-h-[60vh] w-auto max-w-full rounded-lg border border-border-default bg-bg-raised"
          />
          <div
            onClick={(e) => e.stopPropagation()}
            className="grid w-full max-w-4xl gap-5 rounded-xl border border-border-default bg-bg-raised/70 p-5 backdrop-blur-md sm:grid-cols-2"
          >
            <div>
              <p className="font-mono text-[10px] uppercase tracking-[0.16em] text-brand-400">
                logic
              </p>
              <p className="mt-1.5 text-[13.5px] leading-relaxed text-fg-muted">
                {lightbox.logic}
              </p>
            </div>
            <div>
              <p className="font-mono text-[10px] uppercase tracking-[0.16em] text-fg-subtle">
                challenge
              </p>
              <p className="mt-1.5 text-[13.5px] leading-relaxed text-fg-muted">
                {lightbox.challenge}
              </p>
            </div>
          </div>
        </div>
      ) : null}
    </>
  );
}
